name: Firebase synchronization
on:
  # schedule:
  # 60분마다 실행 (UTC 기준, test)
  # - cron: '0 * * * *'
  # 테스트를 위해 수동 실행 버튼 활성화
  workflow_dispatch:

jobs:
  call_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Firebase 데이터 동기화
        run: |
          # url 변경
          curl -X GET "https://syncfootballtofirebase-ntic65va6q-uc.a.run.app" \
          -H "Authorization: Bearer ${{ secrets.VITE_FOOTBALL_API_KEY }}${{ secrets.VITE_FIREBASE_API_KEY }}" \
          -v
